<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'NightOwl\Module'                        => __DIR__ . '/Module.php',
    'NightOwl\Controller\NightOwlController' => __DIR__ . '/src/NightOwl/Controller/NightOwlController.php',
    'NightOwl\Model\Auth'                    => __DIR__ . '/src/NightOwl/Model/Auth.php',
    'NightOwlTest\Framework\TestCase'        => __DIR__ . '/tests/NightOwl/Framework/TestCase.php',
    'NightOwlTest\SampleTest'                => __DIR__ . '/tests/NightOwl/SampleTest.php',
);
