<div ng-controller="MainController" >
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="<?php echo $this->url('home') ?>">Night Owl</a>
			</div>
			<div class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li><a href="#" ng-click="selected = 'list'">Dark Launch Codes</a></li>
					<li><a href="#" ng-click="selected = 'audit'">Audits</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
	<div class="container">

		<div class="container">

			<div class="row" ng-controller="LoginController" ng-show="selected == 'login'">
				<table>
				<form>
					<tr>
						<td>Username:</td> 
						<td><input type="text" name="user"></td>
					</tr>
					<tr>
						<td>Password:</td> 
						<td><input type="password" name="password"></td>
					</tr>
					<tr><td><input type="submit" value="Login"></td></tr>
				</form>
				</table>
			</div>

			<div class="row" ng-controller="ListController" ng-show="selected == 'list'">
				<div class="btn-group">
					<button class="btn" ng-class="{active: region == 'west'}" ng-click="region = 'west'">West</button>
					<button class="btn" ng-class="{active: region == 'central'}" ng-click="region = 'central'">Central</button>
					<button class="btn" ng-class="{active: region == 'east'}" ng-click="region = 'east'">East</button>
				</div>
				<br/>
				<br/>
				<form id="filter">
					<div id="tree">
						darklaunch / 
						<select ng-model="tree" ng-options="tree.name for tree in config.trees" ng-change="filterResults()">
							<option value="">All Trees</option>
						</select>
						<span ng-show="tree.subtrees">/ <select ng-init="subtree = tree.subtree[0]" ng-model="subtree" ng-options="subtree for subtree in tree.subtrees" ng-change="filterResults()">
							<option value="">All Subtrees</option>
						</select></span>
					</div>
					<input style="clear:both" type="text" name="search">
					<input type="submit" value="Search">
				</form>
				<div ng-repeat="(tree, codes) in launchCodes">
				<table>
					<thead>
						<h3>{{tree}}</h3>
						<tr>
							<td>Key</td>
							<td>Restriction</td>
							<td>Value</td>
							<td>Description</td>
							<td>Available to JS</td>
						</tr>
					</thead>
					<tr ng-repeat="code in codes">
						<td>{{ code.key }}<div style="font-size: 75%">{{ code.createdDate }}</div></td>
						<td><select ng-model="code.restriction" ng-options="restriction for restriction in config.restrictions" ng-change="echo()"></select></td>
						<td><input type="text" ng-model="code.value"></td>
						<td><textarea ng-model="code.description" cols=50></textarea></td>
						<td><input type="checkbox" ng-model="code.isAvailableToJs" ng-checked="code.isAvailableToJs"></td>
						<td><button class="btn" ng-click="switchMode()">Edit</button></td>
						<td><button class="btn" ng-click="deleteCode(code)">Delete</button></td>
					</tr>
				</table>
				</div>
			</div>

			<div class="row" ng-controller="AuditController" ng-show="selected == 'audit'">
				<table>
					<tr ng-repeat="audit in audits">
						<td>{{ audit.key }}</td>
						<td>{{ audit.value }}</td>
					</tr>
				</table>
				{{msg}}
			</div>
		</div>
	</div>
</div>